version: "3"
services:
  nats:
    image: "nats-streaming:alpine"
    hostname: "nats"
    # expose:
    #   - "4222"
    ports:
      - "8222:8222"
      # - "4222:4222"
    # entrypoint: /nats-streaming-server -store file --dir . #uncomment for file persistance
  event_gateway:
    build: ./event_gateway
    depends_on:
      - nats
    expose:
      - "8000"
    ports:
      - "8000:8000"
  consumer:
    build: ./consumer
    depends_on:
      - nats
